### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Mostly for the Kramdown update (2.3.1 has a security fix).

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Note: you may want to review #18 first.

**Comment by Scarzy** [comment]
> Note: you may want to review #18 first.

Is #18 _required_ for this?

**Comment by PeterJCLaw** [comment]
> > Note: you may want to review #18 first.
> 
> Is #18 _required_ for this?

No, the changes are orthogonal, however you may find that reviewing this is considerably easier if you look at #18 first as that PR greatly improves the local setup instructions.

**Comment by PeterJCLaw** [comment]
In case it helps, we're almost certainly already using these versions in production -- here's the versions which GitHub Pages uses: https://pages.github.com/versions/

**Review by sedders123 — APPROVED** [review]

**Pull request merged**
