### PR TITLE
Add spinner

### PR DESCRIPTION
**Pull request by PeterJCLaw**
The IDE has featured a spinner when outstanding requests are being handled for a long time. However the source of the spinner was never clear. This adds a script and template which create an equivalent spinner.

This is needed now due to the change in SR blue, which the spinner in the IDE needs to match.

Note: this spinner currently uses the same blue as the logo _which is different to the official blue_.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Colour issues now recorded in #5.

**Comment by PeterJCLaw** [comment]
@jimmythompson _why_ has this been closed?

**Comment by jimmythompson** [comment]
Sorry, Peter! I switched the branch from gh-pages to master, and Github closed the PR. Please, feel free to re-submit it.

**Comment by PeterJCLaw** [comment]
Hrm, do you not have a "reopen" button available?

**Comment by PeterJCLaw** [comment]
(not sure if that will have helped)

**Comment by PeterJCLaw** [comment]
(I'd been hoping to resolve #5 before merging this.)

**Pull request merged**
